### ISSUE TITLE
Plugin unusable (invisible in protocol search)

### ISSUE THREAD

**Issue by TomCrey** [scipion-em/scipion-em-motioncorr#102]
Hello,
I've just installed Scipion on a new machine (I've been using Scipion for a few months on other machines without any problems) and I've installed several plugins, including Motioncorr. 
However, it's the only one that's marked as installed when I do: `scipion3 installp --help` (the version indicated is 3.16.2) but when I do Ctrl+f to add the protocol, it's nowhere to be found...
I've already tried deleting the plugin and installing earlier versions, but nothing changes. I've also tried redoing the entire Scipion installation, but to no avail...
I've also run the 2 tests proposed on GitHub, I'm posting copies of my temrinal below. 
I hope you can help me. 

-----------------------------------------------------------------------------------------------------------------------

(base) jd250937@gre074125:~$ scipion3 test motioncorr.tests.test_protocols_motioncor.TestMotioncorAlignMovies
Scipion v3.4.0 - Eugenius
Scanning tests...
Loading test/s ['motioncorr.tests.test_protocols_motioncor.TestMotioncorAlignMovies']
[   FAILED ] _FailedTest.tests

Traceback (most recent call last):
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/tests/__init__.py", line 3, in <module>
    from .test_protocols_motioncor import TestMotioncorAlignMovies
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/tests/test_protocols_motioncor.py", line 36, in <module>
    from ..protocols import ProtMotionCorr
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/protocols/__init__.py", line 30, in <module>
    from .protocol_motioncorr_tasks import ProtMotionCorrTasks
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/protocols/protocol_motioncorr_tasks.py", line 34, in <module>
    from emtools.utils import Timer, Pipeline
ImportError: cannot import name 'Pipeline' from 'emtools.utils' (/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/emtools/utils/__init__.py)

[==========] run 1 tests (0.000 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

-----------------------------------------------------------------------------------------------------------------------

(base) jd250937@gre074125:~$ scipion3 test motioncorr.tests.test_protocols_tomo.TestMotioncorTiltSeriesAlignMovies
Scipion v3.4.0 - Eugenius
Scanning tests...
Loading test/s ['motioncorr.tests.test_protocols_tomo.TestMotioncorTiltSeriesAlignMovies']
[   FAILED ] _FailedTest.tests

Traceback (most recent call last):
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 34, in testFailure
    raise self._exception
ImportError: Failed to import test module: tests
Traceback (most recent call last):
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/tests/__init__.py", line 3, in <module>
    from .test_protocols_motioncor import TestMotioncorAlignMovies
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/tests/test_protocols_motioncor.py", line 36, in <module>
    from ..protocols import ProtMotionCorr
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/protocols/__init__.py", line 30, in <module>
    from .protocol_motioncorr_tasks import ProtMotionCorrTasks
  File "/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/motioncorr/protocols/protocol_motioncorr_tasks.py", line 34, in <module>
    from emtools.utils import Timer, Pipeline
ImportError: cannot import name 'Pipeline' from 'emtools.utils' (/homelocal/jd250937/miniconda3/envs/scipion3/lib/python3.8/site-packages/emtools/utils/__init__.py)

[==========] run 1 tests (0.000 secs)

[  FAILED  ] 1 tests

[  PASSED  ] 0 tests

**Comment by rdrighetto** [comment]
+1 having the same issue

**Comment by azazellochg** [comment]
Just fixed it in devel and production. Please update to 3.16.3
