### ISSUE TITLE
_updateOutputSet error

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-em-motioncorr#66]
```
Traceback (most recent call last):
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 201, in run
    self._run()
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1366, in _run
    self._runSteps(startIndex)
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1217, in _runSteps
    self._stepsExecutor.runSteps(self._steps,
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 256, in runSteps
    stepsCheckCallback()
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pwem/protocols/protocol_movies.py", line 249, in _stepsCheck
    self._checkNewOutput()
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/pwem/protocols/protocol_align_movies.py", line 216, in _checkNewOutput
    self._updateOutputSet('outputMovies', movieSet, streamMode)
  File "/programs/x86_64-linux/scipion/3.0.0/.scipion3env/lib/python3.8/site-packages/motioncorr/protocols/protocol_motioncorr.py", line 634, in _updateOutputSet
    og.updateAll(rlnMicrographStartFrame=self.alignFrame0.get())
  File "/programs/x86_64-linux/scipion/3.0.0/external_plugins/scipion-em-relion/relion/convert/convert31.py", line 110, in updateAll
    self.update(og.rlnOpticsGroup, **kwargs)
  File "/programs/x86_64-linux/scipion/3.0.0/external_plugins/scipion-em-relion/relion/convert/convert31.py", line 103, in update
    newOg = og._replace(**kwargs)
  File "/programs/x86_64-linux/scipion/3.0.0/scipion_extlib/python-3.8.6-jhyh/lib/python3.8/collections/__init__.py", line 413, in _replace
    raise ValueError(f'Got unexpected field names: {list(kwds)!r}')
ValueError: Got unexpected field names: ['rlnMicrographStartFrame']
```
[run.stdout.txt](https://github.com/scipion-em/scipion-em-motioncorr/files/8176685/run.stdout.txt)
[run.stderr.txt](https://github.com/scipion-em/scipion-em-motioncorr/files/8176686/run.stderr.txt)

**Comment by azazellochg** [comment]
Resolved after user updated the plugin
